---
- name: Harden SSH configuration
  hosts: "{{ target }}"
  tasks:
  
  - name : Set SSH KexAlgorithms 140-2 Compliant
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      line: 'KexAlgorithms diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,rsa2048-sha256,ecdh-sha2-nistp384'

  - name: Set SSH Ciphers 140-2 Compliant
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      line: 'Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com'

  - name: Set SSH MACs 140-2 Compliant
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      line: 'MACs hmac-sha256,hmac-sha256@ssh.com,hmac-sha2-256,hmac-sha2-256-etm@openssh.com,hmac-sha512,hmac-sha512@ssh.com,hmac-sha2-512,hmac-sha2-512-etm@openssh.com'
    notify: 
     - restart sshd

  - name: Disable SSH root login
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#PermitRootLogin'
      line: 'PermitRootLogin no'  

#Restart SSHD service if changes are made.
  handlers:
   - name: restart sshd
     service:
       name: sshd
       state: restarted
